/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodorderingsystem;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samad
 */
public class Beverages extends javax.swing.JFrame implements MainInterface{
    
     //Creating feilds
    private double Total; 
    private int count;
    
    //Connection settings to database
    private Connection conn;
    private String connectionUrl = "jdbc:mysql://localhost:3306/foodorderingsystem";
    private String username= "sa";
    private String Pass="anjalo9990";

    /**
     * Creates new form Beverage
     */
    public Beverages() {
        initComponents();
          Displayorder() ;
          FormatTable();
         CheckTable();
         GetTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnMeal = new javax.swing.JButton();
        btnFastFood = new javax.swing.JButton();
        btnAppetizers = new javax.swing.JButton();
        btnBeverages = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTopic = new javax.swing.JLabel();
        lblNescafe = new javax.swing.JLabel();
        lblMilkshake = new javax.swing.JLabel();
        lblSoftDrinks = new javax.swing.JLabel();
        lblFruitJuice = new javax.swing.JLabel();
        lblIceCoffee = new javax.swing.JLabel();
        lblWater = new javax.swing.JLabel();
        lblNesName = new javax.swing.JLabel();
        lblNesPrice = new javax.swing.JLabel();
        lblMilkshakes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDrinks = new javax.swing.JLabel();
        lblDrinksPrice = new javax.swing.JLabel();
        lblJuice = new javax.swing.JLabel();
        lblJuicePrice = new javax.swing.JLabel();
        lblMojitoo = new javax.swing.JLabel();
        lblMojitoPrice = new javax.swing.JLabel();
        lblBottledWater = new javax.swing.JLabel();
        lblWaterPrice = new javax.swing.JLabel();
        lblLKR0 = new javax.swing.JLabel();
        lblLKR1 = new javax.swing.JLabel();
        lblLKR2 = new javax.swing.JLabel();
        lblLKR4 = new javax.swing.JLabel();
        lblMojitoPrice1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCheckout = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        lblLKR = new javax.swing.JLabel();
        lblPlateimage = new javax.swing.JLabel();
        btnTrash = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        lblAmount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnMeal.setBackground(new java.awt.Color(0, 204, 0));
        btnMeal.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnMeal.setForeground(new java.awt.Color(255, 255, 255));
        btnMeal.setText("MEALS");
        btnMeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMealMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMealMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMealMousePressed(evt);
            }
        });
        btnMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMealActionPerformed(evt);
            }
        });

        btnFastFood.setBackground(new java.awt.Color(0, 204, 0));
        btnFastFood.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnFastFood.setForeground(new java.awt.Color(255, 255, 255));
        btnFastFood.setText("FAST FOODS");
        btnFastFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFastFoodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFastFoodMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFastFoodMousePressed(evt);
            }
        });

        btnAppetizers.setBackground(new java.awt.Color(0, 204, 0));
        btnAppetizers.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnAppetizers.setForeground(new java.awt.Color(255, 255, 255));
        btnAppetizers.setText("APPETIZERS");
        btnAppetizers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAppetizersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAppetizersMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAppetizersMousePressed(evt);
            }
        });

        btnBeverages.setBackground(new java.awt.Color(0, 204, 0));
        btnBeverages.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnBeverages.setForeground(new java.awt.Color(255, 255, 255));
        btnBeverages.setText("BEVERAGES");
        btnBeverages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBeveragesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBeveragesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBeveragesMousePressed(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new.jpg"))); // NOI18N
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMeal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFastFood, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAppetizers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(btnBeverages, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFastFood, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAppetizers, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBeverages, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblTopic.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTopic.setForeground(new java.awt.Color(0, 204, 0));
        lblTopic.setText("BEVERAGES");

        lblNescafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NES2.jpg"))); // NOI18N
        lblNescafe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblNescafeMousePressed(evt);
            }
        });

        lblMilkshake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ms1.jpg"))); // NOI18N
        lblMilkshake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMilkshakeMousePressed(evt);
            }
        });

        lblSoftDrinks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/soft drinks1.jpg"))); // NOI18N
        lblSoftDrinks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSoftDrinksMousePressed(evt);
            }
        });

        lblFruitJuice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/juice.jpg"))); // NOI18N
        lblFruitJuice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblFruitJuiceMousePressed(evt);
            }
        });

        lblIceCoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ice.jpg"))); // NOI18N
        lblIceCoffee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblIceCoffeeMousePressed(evt);
            }
        });

        lblWater.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/water_1.jpg"))); // NOI18N
        lblWater.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblWaterMousePressed(evt);
            }
        });

        lblNesName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNesName.setText("NESCAFE");

        lblNesPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNesPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblNesPrice.setText("40.00");

        lblMilkshakes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblMilkshakes.setText("MILKSHAKES ");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("300.00");

        lblDrinks.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDrinks.setText("SOFT DRINKS ");

        lblDrinksPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDrinksPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblDrinksPrice.setText("50.00");

        lblJuice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblJuice.setText("FRESH FRUIT JUICE ");

        lblJuicePrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblJuicePrice.setForeground(new java.awt.Color(153, 153, 153));
        lblJuicePrice.setText("200.00");

        lblMojitoo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblMojitoo.setText("ICE COFFEE");

        lblMojitoPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblMojitoPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblMojitoPrice.setText("LKR");

        lblBottledWater.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblBottledWater.setText("BOTTLED DRINKING WATER");

        lblWaterPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblWaterPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblWaterPrice.setText("LKR  80.00");

        lblLKR0.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLKR0.setForeground(new java.awt.Color(153, 153, 153));
        lblLKR0.setText("LKR");

        lblLKR1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLKR1.setForeground(new java.awt.Color(153, 153, 153));
        lblLKR1.setText("LKR");

        lblLKR2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLKR2.setForeground(new java.awt.Color(153, 153, 153));
        lblLKR2.setText("LKR");

        lblLKR4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLKR4.setForeground(new java.awt.Color(153, 153, 153));
        lblLKR4.setText("LKR");

        lblMojitoPrice1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblMojitoPrice1.setForeground(new java.awt.Color(153, 153, 153));
        lblMojitoPrice1.setText("100.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFruitJuice, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJuice))
                .addGap(101, 101, 101)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblMojitoPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMojitoPrice1)
                        .addGap(171, 171, 171)
                        .addComponent(lblWaterPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblMilkshakes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWater, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDrinks)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblMojitoo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(lblBottledWater, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(485, 485, 485))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(lblLKR1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblJuicePrice))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(lblLKR0, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lblNescafe, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(136, 136, 136)
                        .addComponent(lblLKR2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNesName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(219, 219, 219)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblIceCoffee)
                                    .addComponent(lblMilkshake))
                                .addGap(102, 102, 102)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(lblLKR4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDrinksPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblSoftDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(lblTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTopic)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMilkshake, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNescafe, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoftDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNesName)
                    .addComponent(lblMilkshakes)
                    .addComponent(lblDrinks))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLKR2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLKR4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLKR0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrinksPrice))
                .addGap(66, 66, 66)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFruitJuice)
                    .addComponent(lblIceCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWater, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJuice)
                    .addComponent(lblMojitoo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBottledWater))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJuicePrice)
                    .addComponent(lblLKR1)
                    .addComponent(lblMojitoPrice)
                    .addComponent(lblMojitoPrice1)
                    .addComponent(lblWaterPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jPanel3MouseWheelMoved(evt);
            }
        });

        btnCheckout.setBackground(new java.awt.Color(0, 204, 0));
        btnCheckout.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCheckout.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckout.setText("CHECKOUT");
        btnCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCheckoutMousePressed(evt);
            }
        });
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(153, 153, 153));
        lblTotal.setText("TOTAL");

        lblLKR.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLKR.setForeground(new java.awt.Color(153, 153, 153));
        lblLKR.setText("LKR");

        lblPlateimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EmptyPlate.jpeg"))); // NOI18N

        btnTrash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trash.png"))); // NOI18N
        btnTrash.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTrash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTrashMousePressed(evt);
            }
        });
        btnTrash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrashActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_down_48px_5.png"))); // NOI18N
        btnRefresh.setText("VIEW PLATE");
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRefreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRefreshMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRefreshMousePressed(evt);
            }
        });

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item No", "Product Description", "qty", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderTable);

        lblAmount.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAmount.setForeground(new java.awt.Color(153, 153, 153));
        lblAmount.setText("0.00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblPlateimage))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblLKR, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTrash, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnRefresh))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTrash, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblPlateimage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLKR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1375, 744));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMealMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealMouseEntered

        // Changing the Fastfood button background color, when cursor move to the Fastfood button
        btnMeal.setBackground(new Color(0,102,0));
        btnBeverages.setBackground(Color.GREEN);  

    }//GEN-LAST:event_btnMealMouseEntered

    private void btnMealMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealMouseExited

        // Rechange the Fastfood button & Beverages button background colors, when cursor move out the Fastfood button
        btnMeal.setBackground(Color.GREEN);
        btnBeverages.setBackground(new Color(0,102,0));
        btnBeverages.setForeground(Color.WHITE);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnMealMouseExited

    private void btnMealMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealMousePressed
        Meal ml = new Meal();
        ml.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnMealMousePressed

    private void btnFastFoodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFastFoodMouseEntered

        // Changing the Meal button background color, when cursor move to the Meal button
        btnFastFood.setBackground(new Color(0,102,0));
        btnBeverages.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnFastFoodMouseEntered

    private void btnFastFoodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFastFoodMouseExited

        // Rechange the Meal button & Beverages button background colors, when cursor move out the Meal button
        btnFastFood.setBackground(Color.GREEN);
        btnBeverages.setBackground(new Color(0,102,0));
        btnBeverages.setForeground(Color.WHITE);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnFastFoodMouseExited

    private void btnFastFoodMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFastFoodMousePressed
        Fastfood fd = new Fastfood();
        fd.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnFastFoodMousePressed

    private void btnAppetizersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppetizersMouseEntered

        // Changing the Appetizers button background color, when cursor move to the Appertizer button
        btnAppetizers.setBackground(new Color(0,102,0));
        btnBeverages.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnAppetizersMouseEntered

    private void btnAppetizersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppetizersMouseExited

        // Rechange the Appetizers button & Bevearges button background colors, when cursor move out of the Appetizers button
        btnAppetizers.setBackground(Color.GREEN);
        btnBeverages.setBackground(new Color(0,102,0));
        btnBeverages.setForeground(Color.WHITE);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAppetizersMouseExited

    private void btnAppetizersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppetizersMousePressed
        Appetizers ap = new Appetizers();
        ap.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnAppetizersMousePressed

    private void btnBeveragesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeveragesMouseEntered

        // Changing the Beverages button background color, when cursor move to the Beveragesbutton
        btnBeverages.setForeground(Color.GREEN);
        btnBeverages.setBackground(new Color(0,102,0));

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBeveragesMouseEntered

    private void btnBeveragesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeveragesMouseExited

        // Rechange the Beverages button background color, when cursor move out the Beverages button
        btnBeverages.setBackground(new Color(0,102,0));
        btnBeverages.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBeveragesMouseExited

    private void btnBeveragesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeveragesMousePressed
        Beverages bv = new Beverages();
        bv.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnBeveragesMousePressed

    private void lblNescafeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNescafeMousePressed

        POPUP_Message_Nescafe ns = new POPUP_Message_Nescafe();
        ns.setVisible(true);
       DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
       model.setRowCount(0);
       Displayorder();
       GetTotal();
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNescafeMousePressed

    private void lblMilkshakeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMilkshakeMousePressed

        POPUP_Message_Milkshakes ms = new POPUP_Message_Milkshakes();
        ms.setVisible(true);

        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        model.setRowCount(0);
        Displayorder();
        GetTotal();

        // TODO add your handling code here:
    }//GEN-LAST:event_lblMilkshakeMousePressed

    private void lblSoftDrinksMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoftDrinksMousePressed

        POPUP_Message_Softdrinks sd = new POPUP_Message_Softdrinks();
        sd.setVisible(true);

        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        model.setRowCount(0);
        Displayorder();
        GetTotal();
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSoftDrinksMousePressed

    private void lblFruitJuiceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFruitJuiceMousePressed

        POPUP_Message_FruitJuice fj = new POPUP_Message_FruitJuice();
        fj.setVisible(true);

        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        model.setRowCount(0);
        Displayorder();
        GetTotal();

        // TODO add your handling code here:
    }//GEN-LAST:event_lblFruitJuiceMousePressed

    private void lblIceCoffeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIceCoffeeMousePressed

        POPUP_Message_IceCoffee m = new POPUP_Message_IceCoffee();
        m.setVisible(true);

        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        model.setRowCount(0);
        Displayorder();
        GetTotal();

        // TODO add your handling code here:
    }//GEN-LAST:event_lblIceCoffeeMousePressed

    private void lblWaterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWaterMousePressed

        POPUP_Message_Water w = new POPUP_Message_Water();
        w.setVisible(true);

        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        model.setRowCount(0);
        Displayorder();
        GetTotal();

        // TODO add your handling code here:
    }//GEN-LAST:event_lblWaterMousePressed

    private void btnCheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseClicked

        // Going to the next page, which is Order Details Page and hide this page
        if(count == 0)
        {
            JOptionPane.showMessageDialog(null,"Please select food items!");
        }
        else
        {
            //Selecting_DineIn_or_TakeAway od = new Selecting_DineIn_or_TakeAway();
            //od.setVisible(true); 
            //this.hide();
        }        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckoutMouseClicked

    private void btnCheckoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseEntered

        btnCheckout.setBackground(Color.RED);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckoutMouseEntered

    private void btnCheckoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseExited

        btnCheckout.setBackground(Color.GREEN);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckoutMouseExited

    private void btnCheckoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMousePressed
      Order_Details od= new  Order_Details();
       this.hide();
       od.show();
    }//GEN-LAST:event_btnCheckoutMousePressed

    private void btnTrashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrashMousePressed

        Deleteorder();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrashMousePressed

    private void btnRefreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseEntered

        // Changing the Refresh button background color, when cursor move to the Refresh button
        btnRefresh.setBackground(Color.RED);
        btnRefresh.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshMouseEntered

    private void btnRefreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseExited

        // Rechange the Refresh button background color, when cursor move out the Refresh button
        btnRefresh.setBackground(Color.GREEN);
        btnRefresh.setForeground(Color.WHITE);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshMouseExited

    private void btnRefreshMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMousePressed

        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        model.setRowCount(0);
        Displayorder();
        GetTotal();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshMousePressed

    private void jPanel3MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jPanel3MouseWheelMoved

        GetTotal();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseWheelMoved

    private void btnTrashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrashActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize.width, screenSize.height);
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void btnMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMealActionPerformed

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshMouseClicked

    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseClicked
        // TODO add your handling code here:
        Home hm = new Home();
        hm.show();
        this.hide();
    }//GEN-LAST:event_lblLogoMouseClicked

    
    
    //Display Order
    @Override
    public  void Displayorder()
    {
        String qry="SELECT * FROM salesorder";
      
        try
        {
            conn = DriverManager.getConnection(connectionUrl, username, Pass);
            Statement st=conn.prepareStatement(qry);
            ResultSet rs=st.executeQuery(qry);
      
            while(rs.next())
            {
                String item   =String.valueOf(rs.getInt("ItemNo"));
                String Des   = rs.getString("Product");
                String qty   = String.valueOf(rs.getInt("QTY"));
                String price =String.valueOf(rs.getInt("Total"));
                String tbdata[]={item,Des,qty,price};
                DefaultTableModel model=(DefaultTableModel)orderTable.getModel();
                model.addRow(new Object[]{item,Des, qty, price});
            }      
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Something went wrong!\n");
        }
        finally
        {
           CheckTable();
           FormatTable();
        }       
    } 
   
    
   //Delete Order
    @Override
    public void Deleteorder()
    {    
        DefaultTableModel model = (DefaultTableModel)orderTable.getModel();
          
        int row = orderTable.getSelectedRow();
         
        String cell = orderTable.getModel().getValueAt(row, 0).toString();
         
        String qry = "DELETE FROM salesorder WHERE ItemNo = " + cell;
          
        try
        {
            Statement st = conn.prepareStatement(qry);
            st.execute(qry);
            JOptionPane.showMessageDialog(null,"Plate updated!");
        }
        catch(SQLException e )
        {
           e.printStackTrace();
           JOptionPane.showMessageDialog(null,"Error!");
        }
        finally
        {
           CheckTable();
           FormatTable();
        }
    }    
  
   
    //Checking table
    @Override
    public void  CheckTable() 
    {
        
        PreparedStatement stmt = null;
        ResultSet rs = null;
        String qry = " SELECT * From SALESORDER ";

        try 
        {
            conn = DriverManager.getConnection(connectionUrl, username, Pass);
            stmt = (PreparedStatement) conn.prepareStatement(qry);
            rs =  stmt.executeQuery();
            setCount(0);
            
            while(rs.next())
            {
               setCount(getCount() + 1);
            }
            if(count == 0)
            { 
                jScrollPane1.hide();
                orderTable.setVisible(false);
                btnTrash.setVisible(false);
                lblLKR.setVisible(false);
                lblPlateimage.show();
                lblAmount.hide();
            }
            else
            {
                jScrollPane1.show();
                orderTable.setVisible(true);
                btnTrash.setVisible(true);
                lblLKR.setVisible(true);
                lblPlateimage.hide();
                lblAmount.show();
            }
        
        } 
        catch (SQLException ex) 
        {
            ex.printStackTrace();
        }         
    }
        
    
    //Format table  
    @Override
    public void FormatTable() 
    {
        orderTable.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,15));
        orderTable.getTableHeader().setOpaque(true);
        orderTable.getTableHeader().setBackground(new Color(32,136,203));
        orderTable.getTableHeader().setForeground(new Color(255,255,255));
        orderTable.setRowHeight(25);   
    }

    
    //Get Total
    @Override
    public void GetTotal() 
    {
        PreparedStatement pst = null;
        ResultSet rs = null;
        String qry = "Select Sum(Total) as sumprice from salesorder";
       
        try
        {
            conn = DriverManager.getConnection(connectionUrl, username, Pass);
            pst=conn.prepareStatement(qry);
            rs=pst.executeQuery();
            
            if(rs.next())
            {
                String sum = rs.getString("sumprice");
                lblAmount.setText(sum);
            }
        }
       catch (SQLException ex) 
        {
            ex.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beverages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beverages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beverages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beverages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beverages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppetizers;
    private javax.swing.JButton btnBeverages;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnFastFood;
    private javax.swing.JButton btnMeal;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTrash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblBottledWater;
    private javax.swing.JLabel lblDrinks;
    private javax.swing.JLabel lblDrinksPrice;
    private javax.swing.JLabel lblFruitJuice;
    private javax.swing.JLabel lblIceCoffee;
    private javax.swing.JLabel lblJuice;
    private javax.swing.JLabel lblJuicePrice;
    private javax.swing.JLabel lblLKR;
    private javax.swing.JLabel lblLKR0;
    private javax.swing.JLabel lblLKR1;
    private javax.swing.JLabel lblLKR2;
    private javax.swing.JLabel lblLKR4;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMilkshake;
    private javax.swing.JLabel lblMilkshakes;
    private javax.swing.JLabel lblMojitoPrice;
    private javax.swing.JLabel lblMojitoPrice1;
    private javax.swing.JLabel lblMojitoo;
    private javax.swing.JLabel lblNesName;
    private javax.swing.JLabel lblNesPrice;
    private javax.swing.JLabel lblNescafe;
    private javax.swing.JLabel lblPlateimage;
    private javax.swing.JLabel lblSoftDrinks;
    private javax.swing.JLabel lblTopic;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblWater;
    private javax.swing.JLabel lblWaterPrice;
    private javax.swing.JTable orderTable;
    // End of variables declaration//GEN-END:variables


    /**
     * @return the Total
     */
    public double getTotal() {
        return Total;
    }

    /**
     * @param Total the Total to set
     */
    public void setTotal(double Total) {
        this.Total = Total;
    }

    /**
     * @return the count
     */
    public int getCount() {
        return count;
    }

    /**
     * @param count the count to set
     */
    public void setCount(int count) {
        this.count = count;
    }
}





