   /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodorderingsystem;

//Import classes
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Neranji Sulakshika
 */
public class Fastfood extends javax.swing.JFrame implements MainInterface {

    //Creating feilds
    public double Total=0.0;
    int count;
    
    //Connection settings to database
    private Connection conn;
    private String connectionUrl = "jdbc:mysql://localhost:3306/foodorderingsystem";
    private String username= "sa";
    private String Pass="anjalo9990";
    
    /**
     * Creates new form Fast foods
     */
    public Fastfood() {
        initComponents();
        Displayorder() ;
        FormatTable();
        CheckTable();
        GetTotal();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        pnlFastfood = new javax.swing.JPanel();
        pnlMenuPanel = new javax.swing.JPanel();
        lblFASTFOOD = new javax.swing.JLabel();
        btnBurger = new javax.swing.JButton();
        btnSubmarine = new javax.swing.JButton();
        btnHotDog = new javax.swing.JButton();
        btnPizza = new javax.swing.JButton();
        btnSandwitch = new javax.swing.JButton();
        btnDonut = new javax.swing.JButton();
        lblBurger = new javax.swing.JLabel();
        lblSubmarine = new javax.swing.JLabel();
        lblHotDog = new javax.swing.JLabel();
        lblPizza = new javax.swing.JLabel();
        lblSandwitch = new javax.swing.JLabel();
        lblDonut = new javax.swing.JLabel();
        lblLKR1 = new javax.swing.JLabel();
        lblLKR2 = new javax.swing.JLabel();
        lblLKR3 = new javax.swing.JLabel();
        lblLKR4 = new javax.swing.JLabel();
        lblLKR5 = new javax.swing.JLabel();
        lblLKR6 = new javax.swing.JLabel();
        lblBurgerPrice = new javax.swing.JLabel();
        lblSubmarinePrice = new javax.swing.JLabel();
        lblHotDogPrice = new javax.swing.JLabel();
        lblPizzaPrice = new javax.swing.JLabel();
        lblSandwitchPrice = new javax.swing.JLabel();
        lblDonutPrice = new javax.swing.JLabel();
        pnlSidePanel = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnMeal = new javax.swing.JButton();
        btnFastfood = new javax.swing.JButton();
        btnAppetizers = new javax.swing.JButton();
        btnBeverages = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ordertable = new javax.swing.JTable();
        lblTotalName = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        btnTrash = new javax.swing.JButton();
        lblPlateImage = new javax.swing.JLabel();
        btnCheckout = new javax.swing.JButton();
        btnViewPlate = new javax.swing.JButton();
        lblLKR = new javax.swing.JLabel();

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("TOTAL");

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("LKR");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("0.00");

        jButton7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton7.setText("ADD TO CART");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlFastfood.setBackground(new java.awt.Color(255, 255, 255));

        pnlMenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblFASTFOOD.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblFASTFOOD.setForeground(new java.awt.Color(51, 204, 0));
        lblFASTFOOD.setText("FAST FOOD");

        btnBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BURGER.jpg"))); // NOI18N
        btnBurger.setText("jButton1");
        btnBurger.setBorder(null);
        btnBurger.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBurger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBurgerMouseClicked(evt);
            }
        });
        btnBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBurgerActionPerformed(evt);
            }
        });

        btnSubmarine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SUBMARINE.jpg"))); // NOI18N
        btnSubmarine.setText("jButton2");
        btnSubmarine.setBorder(null);
        btnSubmarine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmarine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmarineMouseClicked(evt);
            }
        });

        btnHotDog.setBackground(new java.awt.Color(51, 51, 51));
        btnHotDog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HOTDOG.jpg"))); // NOI18N
        btnHotDog.setText("jButton3");
        btnHotDog.setBorder(null);
        btnHotDog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHotDog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHotDogMouseClicked(evt);
            }
        });

        btnPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PIZZA.jpg"))); // NOI18N
        btnPizza.setText("jButton4");
        btnPizza.setBorder(null);
        btnPizza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPizzaMouseClicked(evt);
            }
        });

        btnSandwitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SANDWITCH.jpg"))); // NOI18N
        btnSandwitch.setText("jButton5");
        btnSandwitch.setBorder(null);
        btnSandwitch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSandwitch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSandwitchMouseClicked(evt);
            }
        });

        btnDonut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DONUT.jpg"))); // NOI18N
        btnDonut.setText("jButton6");
        btnDonut.setBorder(null);
        btnDonut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDonut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDonutMouseClicked(evt);
            }
        });

        lblBurger.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblBurger.setText("CHEESE BURGER");
        lblBurger.setToolTipText("");

        lblSubmarine.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSubmarine.setText("SUBMARINE");

        lblHotDog.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblHotDog.setText("HOT DOG");

        lblPizza.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPizza.setText("PIZZA");

        lblSandwitch.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSandwitch.setText("SANDWICH");

        lblDonut.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDonut.setText("DONUT");

        lblLKR1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLKR1.setForeground(new java.awt.Color(153, 153, 153));
        lblLKR1.setText("LKR");

        lblLKR2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLKR2.setForeground(new java.awt.Color(153, 153, 153));
        lblLKR2.setText("LKR");

        lblLKR3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLKR3.setForeground(new java.awt.Color(153, 153, 153));
        lblLKR3.setText("LKR");

        lblLKR4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLKR4.setForeground(new java.awt.Color(153, 153, 153));
        lblLKR4.setText("LKR");

        lblLKR5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLKR5.setForeground(new java.awt.Color(153, 153, 153));
        lblLKR5.setText("LKR");

        lblLKR6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLKR6.setForeground(new java.awt.Color(153, 153, 153));
        lblLKR6.setText("LKR");

        lblBurgerPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblBurgerPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblBurgerPrice.setText("200.00");

        lblSubmarinePrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSubmarinePrice.setForeground(new java.awt.Color(153, 153, 153));
        lblSubmarinePrice.setText("200.00");

        lblHotDogPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblHotDogPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblHotDogPrice.setText("150.00");

        lblPizzaPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPizzaPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblPizzaPrice.setText("150.00");

        lblSandwitchPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSandwitchPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblSandwitchPrice.setText("100.00");

        lblDonutPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDonutPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblDonutPrice.setText("60.00");

        javax.swing.GroupLayout pnlMenuPanelLayout = new javax.swing.GroupLayout(pnlMenuPanel);
        pnlMenuPanel.setLayout(pnlMenuPanelLayout);
        pnlMenuPanelLayout.setHorizontalGroup(
            pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblLKR1)
                        .addGap(18, 18, 18)
                        .addComponent(lblBurgerPrice))
                    .addComponent(btnBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblBurger)))
                .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMenuPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnSubmarine, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnHotDog, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubmarine)
                            .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                                .addComponent(lblLKR2)
                                .addGap(18, 18, 18)
                                .addComponent(lblSubmarinePrice)))
                        .addGap(151, 151, 151)
                        .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                                .addComponent(lblLKR3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblHotDogPrice))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblHotDog)
                                .addGap(18, 18, 18)))
                        .addGap(157, 157, 157))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuPanelLayout.createSequentialGroup()
                .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFASTFOOD, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                                        .addComponent(lblPizza)
                                        .addGap(81, 81, 81))
                                    .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                                        .addComponent(lblLKR4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPizzaPrice)
                                        .addGap(48, 48, 48)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSandwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSandwitch)
                                    .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                                        .addComponent(lblLKR5)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblSandwitchPrice)))))))
                .addGap(63, 63, 63)
                .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDonut, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuPanelLayout.createSequentialGroup()
                                .addComponent(lblDonut)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuPanelLayout.createSequentialGroup()
                                .addComponent(lblLKR6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDonutPrice)))))
                .addGap(115, 115, 115))
        );
        pnlMenuPanelLayout.setVerticalGroup(
            pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDonut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDonut)
                        .addGap(18, 18, 18)
                        .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLKR6)
                            .addComponent(lblDonutPrice)))
                    .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                        .addComponent(lblFASTFOOD, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                                .addComponent(lblBurger)
                                .addGap(12, 12, 12)
                                .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLKR1)
                                    .addComponent(lblBurgerPrice)))
                            .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                                .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSubmarine, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnHotDog, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                                        .addComponent(lblSubmarine)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblLKR2)
                                            .addComponent(lblSubmarinePrice))
                                        .addGap(6, 6, 6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuPanelLayout.createSequentialGroup()
                                        .addComponent(lblHotDog)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblLKR3)
                                            .addComponent(lblHotDogPrice))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                                .addComponent(btnPizza)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPizza)
                                .addGap(18, 18, 18)
                                .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLKR4)
                                    .addComponent(lblPizzaPrice)))
                            .addGroup(pnlMenuPanelLayout.createSequentialGroup()
                                .addComponent(btnSandwitch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSandwitch)
                                .addGap(18, 18, 18)
                                .addGroup(pnlMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLKR5)
                                    .addComponent(lblSandwitchPrice))))))
                .addGap(22, 22, 22))
        );

        lblFASTFOOD.getAccessibleContext().setAccessibleName("lblFASTFOOD");
        btnBurger.getAccessibleContext().setAccessibleName("btnBurger");
        btnSubmarine.getAccessibleContext().setAccessibleName("btnSubmarine");
        btnSubmarine.getAccessibleContext().setAccessibleDescription("");
        btnHotDog.getAccessibleContext().setAccessibleName("btnHotDog");
        btnPizza.getAccessibleContext().setAccessibleName("btnPizza");
        btnSandwitch.getAccessibleContext().setAccessibleName("btnSandwitch");
        btnDonut.getAccessibleContext().setAccessibleName("btnDonut");
        lblLKR1.getAccessibleContext().setAccessibleName("lblLKR1");
        lblLKR2.getAccessibleContext().setAccessibleName("lblLKR2");
        lblLKR3.getAccessibleContext().setAccessibleName("lblLKR3");
        lblLKR4.getAccessibleContext().setAccessibleName("lblLKR4");
        lblLKR5.getAccessibleContext().setAccessibleName("lblLKR5");
        lblLKR6.getAccessibleContext().setAccessibleName("lblLKR6");
        lblBurgerPrice.getAccessibleContext().setAccessibleName("lblBurgerPrice");
        lblSubmarinePrice.getAccessibleContext().setAccessibleName("lblSubmarinePrice");
        lblHotDogPrice.getAccessibleContext().setAccessibleName("lblHotDogPrice");
        lblPizzaPrice.getAccessibleContext().setAccessibleName("lblPizzaPrice");
        lblSandwitchPrice.getAccessibleContext().setAccessibleName("lblSandwitchPrice");
        lblDonutPrice.getAccessibleContext().setAccessibleName("lblDonutPrice");

        pnlSidePanel.setBackground(new java.awt.Color(255, 255, 255));
        pnlSidePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblLogo.setForeground(new java.awt.Color(51, 51, 51));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        lblLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
        });

        btnMeal.setBackground(new java.awt.Color(0, 204, 0));
        btnMeal.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnMeal.setForeground(new java.awt.Color(255, 255, 255));
        btnMeal.setText("MEAL");
        btnMeal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMeal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMeal.setPreferredSize(new java.awt.Dimension(73, 25));
        btnMeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMealMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMealMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMealMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMealMousePressed(evt);
            }
        });

        btnFastfood.setBackground(new java.awt.Color(0, 102, 0));
        btnFastfood.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnFastfood.setForeground(new java.awt.Color(255, 255, 255));
        btnFastfood.setText("FAST FOOD");
        btnFastfood.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFastfood.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFastfood.setPreferredSize(new java.awt.Dimension(73, 25));
        btnFastfood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFastfoodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFastfoodMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFastfoodMousePressed(evt);
            }
        });
        btnFastfood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFastfoodActionPerformed(evt);
            }
        });

        btnAppetizers.setBackground(new java.awt.Color(0, 204, 0));
        btnAppetizers.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnAppetizers.setForeground(new java.awt.Color(255, 255, 255));
        btnAppetizers.setText("APPETIZERS");
        btnAppetizers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAppetizers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAppetizers.setPreferredSize(new java.awt.Dimension(73, 25));
        btnAppetizers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAppetizersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAppetizersMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAppetizersMousePressed(evt);
            }
        });

        btnBeverages.setBackground(new java.awt.Color(0, 204, 0));
        btnBeverages.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnBeverages.setForeground(new java.awt.Color(255, 255, 255));
        btnBeverages.setText("BEVERAGES");
        btnBeverages.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBeverages.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBeverages.setPreferredSize(new java.awt.Dimension(73, 25));
        btnBeverages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBeveragesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBeveragesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBeveragesMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlSidePanelLayout = new javax.swing.GroupLayout(pnlSidePanel);
        pnlSidePanel.setLayout(pnlSidePanelLayout);
        pnlSidePanelLayout.setHorizontalGroup(
            pnlSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(btnMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFastfood, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAppetizers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBeverages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSidePanelLayout.setVerticalGroup(
            pnlSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnFastfood, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnAppetizers, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnBeverages, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        lblLogo.getAccessibleContext().setAccessibleName("lblLogo");
        btnMeal.getAccessibleContext().setAccessibleName("btnMeal");
        btnFastfood.getAccessibleContext().setAccessibleName("btnFastfood");
        btnAppetizers.getAccessibleContext().setAccessibleName("btnAppetizers");
        btnBeverages.getAccessibleContext().setAccessibleName("btnBeverages");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jPanel2MouseWheelMoved(evt);
            }
        });

        Ordertable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Ordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item No", "Product Description", "Qty", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Ordertable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        Ordertable.setAutoscrolls(false);
        Ordertable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ordertable.setFillsViewportHeight(true);
        Ordertable.setGridColor(new java.awt.Color(255, 255, 255));
        Ordertable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        Ordertable.setRowHeight(25);
        Ordertable.setSelectionBackground(new java.awt.Color(232, 57, 95));
        Ordertable.setShowHorizontalLines(false);
        Ordertable.setSurrendersFocusOnKeystroke(true);
        Ordertable.setUpdateSelectionOnSort(false);
        jScrollPane2.setViewportView(Ordertable);
        if (Ordertable.getColumnModel().getColumnCount() > 0) {
            Ordertable.getColumnModel().getColumn(0).setPreferredWidth(25);
            Ordertable.getColumnModel().getColumn(1).setPreferredWidth(100);
            Ordertable.getColumnModel().getColumn(2).setPreferredWidth(20);
            Ordertable.getColumnModel().getColumn(3).setPreferredWidth(25);
        }
        Ordertable.getAccessibleContext().setAccessibleName("Ordertable");

        lblTotalName.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        lblTotalName.setForeground(new java.awt.Color(51, 204, 0));
        lblTotalName.setText("TOTAL");

        lblTotalPrice.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTotalPrice.setText("00.00");

        btnTrash.setBackground(new java.awt.Color(255, 255, 255));
        btnTrash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trash.png"))); // NOI18N
        btnTrash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTrashMousePressed(evt);
            }
        });

        lblPlateImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EmptyPlate.jpeg"))); // NOI18N

        btnCheckout.setBackground(new java.awt.Color(0, 153, 0));
        btnCheckout.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnCheckout.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckout.setText("CHECKOUT");
        btnCheckout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCheckout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheckout.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseMoved(evt);
            }
        });
        btnCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCheckoutMousePressed(evt);
            }
        });
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        btnViewPlate.setBackground(new java.awt.Color(0, 153, 0));
        btnViewPlate.setFont(new java.awt.Font("Algerian", 1, 24));
        btnViewPlate.setForeground(new java.awt.Color(255, 255, 255));
        btnViewPlate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_down_48px_5.png"))); // NOI18N
        btnViewPlate.setText("View Plate");
        btnViewPlate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewPlate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewPlate.setIconTextGap(1);
        btnViewPlate.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnViewPlateMouseMoved(evt);
            }
        });
        btnViewPlate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewPlateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewPlateMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnViewPlateMousePressed(evt);
            }
        });
        btnViewPlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPlateActionPerformed(evt);
            }
        });

        lblLKR.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblLKR.setText("LKR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnViewPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblTotalName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblLKR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)))
                                .addGap(41, 41, 41))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPlateImage, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnTrash, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(86, Short.MAX_VALUE)
                    .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(59, 59, 59)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnViewPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTrash)
                        .addGap(0, 248, Short.MAX_VALUE))
                    .addComponent(lblPlateImage, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLKR))
                .addGap(71, 71, 71))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(663, Short.MAX_VALUE)
                    .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        lblTotalName.getAccessibleContext().setAccessibleName("lblTotalName");
        lblTotalPrice.getAccessibleContext().setAccessibleName("lblTotalPrice");
        btnTrash.getAccessibleContext().setAccessibleName("btnTrash");
        lblPlateImage.getAccessibleContext().setAccessibleName("lblPlateImage");
        btnCheckout.getAccessibleContext().setAccessibleName("btnCheckout");
        btnViewPlate.getAccessibleContext().setAccessibleName("btnViewPlate");
        lblLKR.getAccessibleContext().setAccessibleName("lblLKR");

        javax.swing.GroupLayout pnlFastfoodLayout = new javax.swing.GroupLayout(pnlFastfood);
        pnlFastfood.setLayout(pnlFastfoodLayout);
        pnlFastfoodLayout.setHorizontalGroup(
            pnlFastfoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFastfoodLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(678, 678, 678))
        );
        pnlFastfoodLayout.setVerticalGroup(
            pnlFastfoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFastfoodLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFastfoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlMenuPanel.getAccessibleContext().setAccessibleName("pnlMenuPanel");
        pnlSidePanel.getAccessibleContext().setAccessibleName("pnlSidePanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFastfood, javax.swing.GroupLayout.PREFERRED_SIZE, 1360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFastfood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlFastfood.getAccessibleContext().setAccessibleName("pnlFastfood");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPizzaActionPerformed

    private void btnMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMealActionPerformed

    private void btnBurgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBurgerMouseClicked
        // Show PopUp Burger Message
        POPUP_Message_Burger bp = new POPUP_Message_Burger();
        bp.setVisible(true);
        
        // Displaying the number of Chicken Burgers we added to the plate
        DefaultTableModel model = (DefaultTableModel) Ordertable.getModel();
        model.setRowCount(0);
        Displayorder();
        GetTotal();
    }//GEN-LAST:event_btnBurgerMouseClicked

    private void btnSubmarineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmarineMouseClicked
        // Show PopUp Submarine Message
        POPUP_Message_Submarine bp = new POPUP_Message_Submarine();
        bp.setVisible(true);
        
        // Displaying the number of Submarine buns we added to the plate
        DefaultTableModel model = (DefaultTableModel) Ordertable.getModel();
        model.setRowCount(0);
        Displayorder();
        GetTotal();
    }//GEN-LAST:event_btnSubmarineMouseClicked

    private void btnHotDogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHotDogMouseClicked
        // Show PopUp Hot Dog Message
        POPUP_Message_HotDog bp = new POPUP_Message_HotDog();
        bp.setVisible(true);
        
        // Displaying the number of HotDogs we added to the plate
        DefaultTableModel model = (DefaultTableModel) Ordertable.getModel();
        model.setRowCount(0);
        Displayorder();
        GetTotal();
    }//GEN-LAST:event_btnHotDogMouseClicked

    private void btnPizzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPizzaMouseClicked
        // Show PopUp Pizza Message
        POPUP_Message_Pizza bp = new POPUP_Message_Pizza();
        bp.setVisible(true);
        
        // Displaying the number of Pizzas we added to the plate
        DefaultTableModel model = (DefaultTableModel) Ordertable.getModel();
        model.setRowCount(0);
        Displayorder();
        GetTotal();
    }//GEN-LAST:event_btnPizzaMouseClicked

    private void btnSandwitchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSandwitchMouseClicked
        // Show PopUp Sandwitch Message
        POPUP_Message_Sandwitch bp = new POPUP_Message_Sandwitch();
        bp.setVisible(true);
        
        // Displaying the number of Sandwitches we added to the plate
        DefaultTableModel model = (DefaultTableModel) Ordertable.getModel();
        model.setRowCount(0);
        Displayorder();
        GetTotal();
    }//GEN-LAST:event_btnSandwitchMouseClicked

    private void btnDonutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDonutMouseClicked
        // Show PopUp Donut Message
        POPUP_Message_Donut bp = new POPUP_Message_Donut();
        bp.setVisible(true);
        
        // Displaying the number of Donuts we added to the plate
        DefaultTableModel model = (DefaultTableModel) Ordertable.getModel();
        model.setRowCount(0);
        Displayorder();
        GetTotal();
    }//GEN-LAST:event_btnDonutMouseClicked

    private void btnMealMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealMouseEntered
        // Rechange the Meal button & Fastfood button background colors, when cursor move out the Meal button
        btnMeal.setBackground(new Color(0,102,0));
        btnFastfood.setBackground(Color.GREEN);       
    }//GEN-LAST:event_btnMealMouseEntered

    private void btnMealMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealMouseExited
        // Rechange the Meal button & Fastfood button background colors, when cursor move out the Meal button
        btnMeal.setBackground(Color.GREEN);
        btnFastfood.setBackground(new Color(0,102,0));
        btnFastfood.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnMealMouseExited

    private void btnFastfoodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFastfoodMouseEntered
        // Changing the Fastfood button background color, when cursor move to the Fastfood button
        btnFastfood.setForeground(Color.GREEN);
        btnFastfood.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_btnFastfoodMouseEntered

    private void btnFastfoodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFastfoodMouseExited
        // Rechange the Fastfood button background color, when cursor move out the Fastfood button
        btnFastfood.setBackground(new Color(0,102,0));
        btnFastfood.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnFastfoodMouseExited

    private void btnAppetizersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppetizersMouseEntered
        // Changing the Appetizers button & Fastfood button background colors, when cursor move to the Appetizers button
        btnAppetizers.setBackground(new Color(0,102,0));
        btnFastfood.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnAppetizersMouseEntered

    private void btnAppetizersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppetizersMouseExited
        // Rechange the Appetizers button & Fastfood button background colors, when cursor move out the Appetizers button
        btnAppetizers.setBackground(Color.GREEN);
        btnFastfood.setBackground(new Color(0,102,0));
        btnFastfood.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnAppetizersMouseExited

    private void btnBeveragesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeveragesMouseEntered
        // Changing the Beverages button & Fastfood button background colors, when cursor move to the Beverages button
        btnBeverages.setBackground(new Color(0,102,0));
        btnFastfood.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnBeveragesMouseEntered

    private void btnBeveragesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeveragesMouseExited
        // Rechange the Beverages button & Fastfood button background colors, when cursor move out the Beverages button
        btnBeverages.setBackground(Color.GREEN);
        btnFastfood.setBackground(new Color(0,102,0));
        btnFastfood.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBeveragesMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // This display the Frame into middle of the screen
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize.width, screenSize.height);
    }//GEN-LAST:event_formWindowOpened

    private void btnMealMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealMousePressed
        // Shifting to the Meal page
        Meal ml = new Meal();
        ml.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnMealMousePressed

    private void btnAppetizersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppetizersMousePressed
        //Shifting to the Appetizers page
        Appetizers ap = new Appetizers();
        ap.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnAppetizersMousePressed

    private void btnBeveragesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeveragesMousePressed
        //Shifting to the Beverages page
        Beverages bv = new Beverages();
        bv.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnBeveragesMousePressed

    private void btnFastfoodMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFastfoodMousePressed
        // Only show this page
        this.setVisible(true);
    }//GEN-LAST:event_btnFastfoodMousePressed

    private void btnFastfoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFastfoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFastfoodActionPerformed

    private void btnMealMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMealMouseClicked

    private void btnBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBurgerActionPerformed

    private void pnlMyPlateMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_pnlMyPlateMouseWheelMoved
        // Getting the total price
        GetTotal();
    }//GEN-LAST:event_pnlMyPlateMouseWheelMoved

    private void btnTrashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrashMousePressed
        // Delete selected item, when Trash button pressed
        Deleteorder();
    }//GEN-LAST:event_btnTrashMousePressed

    private void btnViewPlateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewPlateMousePressed
        // Refreshing the order table, when the ViewPlate button pressed
        DefaultTableModel model = (DefaultTableModel) Ordertable.getModel();
        model.setRowCount(0);
        Displayorder();
        GetTotal();
    }//GEN-LAST:event_btnViewPlateMousePressed

    private void btnViewPlateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewPlateMouseExited
        // Rechange the Refresh button background color, when cursor move out the Refresh button
        btnViewPlate.setBackground(Color.GREEN);
        btnViewPlate.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnViewPlateMouseExited

    private void btnViewPlateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewPlateMouseEntered
        // Changing the Refresh button background color, when cursor move to the Refresh button
        btnViewPlate.setBackground(Color.RED);
        btnViewPlate.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnViewPlateMouseEntered

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void btnCheckoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseExited
        // Rechange the Checkout button background color, when cursor move out the Checkout button
        btnCheckout.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnCheckoutMouseExited

    private void btnCheckoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseEntered
        // Changing the Checkout button background color, when cursor move to the Checkout button
        btnCheckout.setBackground(Color.RED);
    }//GEN-LAST:event_btnCheckoutMouseEntered

    private void btnCheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseClicked
              
    }//GEN-LAST:event_btnCheckoutMouseClicked

    private void jPanel2MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jPanel2MouseWheelMoved
        // Getting the total
        GetTotal();
    }//GEN-LAST:event_jPanel2MouseWheelMoved

    private void btnViewPlateMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewPlateMouseMoved
        // Changing the ViewPlate button background color, when cursor move to the ViewPlate button
        btnViewPlate.setBackground(Color.RED);
    }//GEN-LAST:event_btnViewPlateMouseMoved

    private void btnCheckoutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckoutMouseMoved

    private void btnViewPlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPlateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewPlateActionPerformed

    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseClicked
        Home hm = new Home();
        hm.show();
        this.hide();
    }//GEN-LAST:event_lblLogoMouseClicked

    private void btnCheckoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMousePressed
        // Going to the next page, which is Order Details Page and hide this page
        Order_Details od= new  Order_Details();
        this.hide();
        od.show();
    }//GEN-LAST:event_btnCheckoutMousePressed

                                    //Member Methods.... 
    
    //Display Order
    @Override
    public  void Displayorder()
    {
        String qry="SELECT * FROM salesorder";
      
        try
        {
            conn = DriverManager.getConnection(connectionUrl, username, Pass);
            Statement st=conn.prepareStatement(qry);
            ResultSet rs=st.executeQuery(qry);
      
            while(rs.next())
            {
                String item   =String.valueOf(rs.getInt("ItemNo"));
                String Des   = rs.getString("Product");
                String qty   = String.valueOf(rs.getInt("QTY"));
                String price =String.valueOf(rs.getInt("Total"));
                String tbdata[]={item,Des,qty,price};
                DefaultTableModel model=(DefaultTableModel)Ordertable.getModel();
                model.addRow(new Object[]{item,Des, qty, price});
            }      
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Something went wrong!\n");
        }
        finally
        {
           CheckTable();
           FormatTable();
        }       
    } 
   
    
   //Delete Order
    @Override
    public void Deleteorder()
    {    
        DefaultTableModel model = (DefaultTableModel)Ordertable.getModel();
          
        int row = Ordertable.getSelectedRow();
         
        String cell = Ordertable.getModel().getValueAt(row, 0).toString();
         
        String qry = "DELETE FROM salesorder WHERE ItemNo = " + cell;
          
        try
        {
            Statement st = conn.prepareStatement(qry);
            st.execute(qry);
            JOptionPane.showMessageDialog(null,"Plate updated!");
        }
        catch(SQLException e )
        {
           e.printStackTrace();
           JOptionPane.showMessageDialog(null,"Error!");
        }
        finally
        {
           CheckTable();
           FormatTable();
        }
    }    
  
   
    //Checking table
    @Override
    public void  CheckTable() 
    {
        
        PreparedStatement stmt = null;
        ResultSet rs = null;
        String qry = " SELECT * From SALESORDER ";

        try 
        {
            conn = DriverManager.getConnection(connectionUrl, username, Pass);
            stmt = (PreparedStatement) conn.prepareStatement(qry);
            rs =  stmt.executeQuery();
            setCount(0);
            
            while(rs.next())
            {
               setCount(getCount() + 1);
            }
            if(count == 0)
            { 
                jScrollPane2.hide();
                Ordertable.setVisible(false);
                btnTrash.setVisible(false);
                lblLKR.setVisible(false);
                lblPlateImage.show();
                lblTotalPrice.hide();
            }
            else
            {
                jScrollPane2.show();
                Ordertable.setVisible(true);
                btnTrash.setVisible(true);
                lblLKR.setVisible(true);
                lblPlateImage.hide();
                lblTotalPrice.show();
            }
        
        } 
        catch (SQLException ex) 
        {
            ex.printStackTrace();
        }         
    }
        
    
    //Format table  
    @Override
    public void FormatTable() 
    {
        Ordertable.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,15));
        Ordertable.getTableHeader().setOpaque(true);
        Ordertable.getTableHeader().setBackground(new Color(32,136,203));
        Ordertable.getTableHeader().setForeground(new Color(255,255,255));
        Ordertable.setRowHeight(25);   
    }

    
    //Get Total
    @Override
    public void GetTotal() 
    {
        PreparedStatement pst = null;
        ResultSet rs = null;
        String qry = "Select Sum(Total) as sumprice from salesorder";
       
        try
        {
            conn = DriverManager.getConnection(connectionUrl, username, Pass);
            pst=conn.prepareStatement(qry);
            rs=pst.executeQuery();
            
            if(rs.next())
            {
                String sum = rs.getString("sumprice");
                lblTotalPrice.setText(sum);
            }
        }
       catch (SQLException ex) 
        {
            ex.printStackTrace();
        }
    }
    
    
    /**
     * @param args the command line arguments
     */ 
    public static void main(String args[]) {
        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fastfood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ordertable;
    private javax.swing.JButton btnAppetizers;
    private javax.swing.JButton btnBeverages;
    private javax.swing.JButton btnBurger;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnDonut;
    private javax.swing.JButton btnFastfood;
    private javax.swing.JButton btnHotDog;
    private javax.swing.JButton btnMeal;
    private javax.swing.JButton btnPizza;
    private javax.swing.JButton btnSandwitch;
    private javax.swing.JButton btnSubmarine;
    private javax.swing.JButton btnTrash;
    private javax.swing.JButton btnViewPlate;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBurger;
    private javax.swing.JLabel lblBurgerPrice;
    private javax.swing.JLabel lblDonut;
    private javax.swing.JLabel lblDonutPrice;
    private javax.swing.JLabel lblFASTFOOD;
    private javax.swing.JLabel lblHotDog;
    private javax.swing.JLabel lblHotDogPrice;
    private javax.swing.JLabel lblLKR;
    private javax.swing.JLabel lblLKR1;
    private javax.swing.JLabel lblLKR2;
    private javax.swing.JLabel lblLKR3;
    private javax.swing.JLabel lblLKR4;
    private javax.swing.JLabel lblLKR5;
    private javax.swing.JLabel lblLKR6;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPizza;
    private javax.swing.JLabel lblPizzaPrice;
    private javax.swing.JLabel lblPlateImage;
    private javax.swing.JLabel lblSandwitch;
    private javax.swing.JLabel lblSandwitchPrice;
    private javax.swing.JLabel lblSubmarine;
    private javax.swing.JLabel lblSubmarinePrice;
    private javax.swing.JLabel lblTotalName;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JPanel pnlFastfood;
    private javax.swing.JPanel pnlMenuPanel;
    private javax.swing.JPanel pnlSidePanel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the Total
     */
    public double getTotal() 
    {
        return Total;
    }

    /**
     * @param Total the Total to set
     */
    public void setTotal(double Total) 
    {
        this.Total = Total;
    }

    /**
     * @return the count
     */
    public int getCount() 
    {
        return count;
    }

    /**
     * @param count the count to set
     */
    public void setCount(int count) 
    {
        this.count = count;
    }
}
