/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodorderingsystem;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author RYAN
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
          setExtendedState(Meal.MAXIMIZED_BOTH); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bgpanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Orderbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1367, 698));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1367, 698));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Bgpanel.setBackground(new java.awt.Color(255, 255, 255));
        Bgpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Bgpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        Bgpanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 120, 130));

        Orderbtn.setBackground(new java.awt.Color(0, 204, 0));
        Orderbtn.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        Orderbtn.setText("Order Now");
        Orderbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 20, true));
        Orderbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Orderbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                OrderbtnMouseMoved(evt);
            }
        });
        Orderbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Orderbtn(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                OrderbtnMouseExited(evt);
            }
        });
        Bgpanel.add(Orderbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 680, 380, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wa.jpg"))); // NOI18N
        Bgpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bgpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bgpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setLocation(new java.awt.Point(0, 0));
    }// </editor-fold>//GEN-END:initComponents

    private void Orderbtn(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Orderbtn
    Meal ml= new Meal();
    ml.show();
    this.hide();
    }//GEN-LAST:event_Orderbtn

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
   this.setSize(screenSize.width, screenSize.height);
    }//GEN-LAST:event_formWindowOpened

    private void OrderbtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderbtnMouseMoved
          Orderbtn.setBackground(new Color(0,102,0));
          Orderbtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_OrderbtnMouseMoved

    private void OrderbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderbtnMouseExited
       Orderbtn.setBackground(new Color(0,204,0));
       Orderbtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_OrderbtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bgpanel;
    private javax.swing.JButton Orderbtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
