/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodorderingsystem;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import static jdk.nashorn.internal.runtime.PropertyMap.getCount;

/**
 *
 * @author dlsak
 */

public class Order_Details extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    private double Total; 
    private int count;
    //Connection settings to database
    Connection conn;
    String connectionUrl = "jdbc:mysql://localhost:3306/foodorderingsystem";
    String username= "sa";
    String Pass="anjalo9990";
    
    public Order_Details() {
        initComponents();
        this.setExtendedState(Order_Details.MAXIMIZED_BOTH);
           displayorder();
    }

   
    
 
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnCheckout = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ordertable = new javax.swing.JTable();
        Sidepanel = new javax.swing.JPanel();
        FFbtn = new javax.swing.JButton();
        APBTN = new javax.swing.JButton();
        BVGBtn = new javax.swing.JButton();
        Logobtn = new javax.swing.JButton();
        btnMeal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("ORDER DETAILS");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 300, 50));

        btnCheckout.setBackground(new java.awt.Color(0, 204, 0));
        btnCheckout.setFont(new java.awt.Font("Algerian", 1, 30)); // NOI18N
        btnCheckout.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckout.setText("Checkout");
        btnCheckout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCheckout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkbtn(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseExited(evt);
            }
        });
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 620, 220, 90));

        ordertable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item No", "Product Description", "Qty", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ordertable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        ordertable.setAutoscrolls(false);
        ordertable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ordertable.setFillsViewportHeight(true);
        ordertable.setFocusable(false);
        ordertable.setGridColor(new java.awt.Color(255, 255, 255));
        ordertable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        ordertable.setRowHeight(25);
        ordertable.setSelectionBackground(new java.awt.Color(232, 57, 95));
        ordertable.setShowHorizontalLines(false);
        ordertable.setSurrendersFocusOnKeystroke(true);
        ordertable.setUpdateSelectionOnSort(false);
        jScrollPane2.setViewportView(ordertable);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 740, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 1090, 750));

        Sidepanel.setBackground(new java.awt.Color(255, 255, 255));
        Sidepanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        FFbtn.setBackground(new java.awt.Color(0, 204, 0));
        FFbtn.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        FFbtn.setForeground(new java.awt.Color(255, 255, 255));
        FFbtn.setText("Fast Food");
        FFbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FFbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FFbtn.setPreferredSize(new java.awt.Dimension(72, 36));
        FFbtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                FFbtnMouseMoved(evt);
            }
        });
        FFbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FFbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FFbtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FFbtnMousePressed(evt);
            }
        });
        FFbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FFbtnActionPerformed(evt);
            }
        });

        APBTN.setBackground(new java.awt.Color(0, 204, 0));
        APBTN.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        APBTN.setForeground(new java.awt.Color(255, 255, 255));
        APBTN.setText("Apertizers");
        APBTN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        APBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        APBTN.setPreferredSize(new java.awt.Dimension(72, 36));
        APBTN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                APBTNMouseMoved(evt);
            }
        });
        APBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                APBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                APBTNMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                APBTNMousePressed(evt);
            }
        });

        BVGBtn.setBackground(new java.awt.Color(0, 204, 0));
        BVGBtn.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        BVGBtn.setForeground(new java.awt.Color(255, 255, 255));
        BVGBtn.setText("Beverages");
        BVGBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BVGBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BVGBtn.setPreferredSize(new java.awt.Dimension(72, 36));
        BVGBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BVGBtnMouseMoved(evt);
            }
        });
        BVGBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BVGBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BVGBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BVGBtnMousePressed(evt);
            }
        });

        Logobtn.setBackground(new java.awt.Color(255, 255, 255));
        Logobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        Logobtn.setBorder(null);
        Logobtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logobtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogobtnMouseClicked(evt);
            }
        });

        btnMeal.setBackground(new java.awt.Color(0, 204, 0));
        btnMeal.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnMeal.setForeground(new java.awt.Color(255, 255, 255));
        btnMeal.setText("MEAL");
        btnMeal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMeal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMeal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnMealMouseMoved(evt);
            }
        });
        btnMeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMealMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMealMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMealMousePressed(evt);
            }
        });
        btnMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMealActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SidepanelLayout = new javax.swing.GroupLayout(Sidepanel);
        Sidepanel.setLayout(SidepanelLayout);
        SidepanelLayout.setHorizontalGroup(
            SidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BVGBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FFbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(APBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMeal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidepanelLayout.createSequentialGroup()
                .addGap(0, 47, Short.MAX_VALUE)
                .addComponent(Logobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        SidepanelLayout.setVerticalGroup(
            SidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidepanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Logobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(FFbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(APBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(BVGBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(Sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1374, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkbtn(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkbtn

       Payment_Method py= new Payment_Method(); 
       py.setVisible(true);    
       this.hide();
    }//GEN-LAST:event_chkbtn

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
   this.setSize(screenSize.width, screenSize.height);
    }//GEN-LAST:event_formWindowOpened

//fast food start
    private void FFbtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FFbtnMouseMoved
        FFbtn.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_FFbtnMouseMoved

    private void FFbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FFbtnMouseExited
        FFbtn.setBackground(Color.GREEN);
    }//GEN-LAST:event_FFbtnMouseExited

    private void FFbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FFbtnMousePressed
        Fastfood ff= new Fastfood();
        ff.show();
        this.hide();
    }//GEN-LAST:event_FFbtnMousePressed
//fast food end
//appetizer start
    private void APBTNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APBTNMouseMoved
        APBTN.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_APBTNMouseMoved

    private void APBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APBTNMouseExited
        APBTN.setBackground(Color.GREEN);
    }//GEN-LAST:event_APBTNMouseExited

    private void APBTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APBTNMousePressed
        Appetizers ap= new Appetizers();
        ap.show();
        this.hide();
    }//GEN-LAST:event_APBTNMousePressed
//appetizer end
//bevarage start
    private void BVGBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BVGBtnMouseMoved
        BVGBtn.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_BVGBtnMouseMoved

    private void BVGBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BVGBtnMouseExited
        BVGBtn.setBackground(Color.GREEN);
    }//GEN-LAST:event_BVGBtnMouseExited

    private void BVGBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BVGBtnMousePressed
        Beverages bv= new Beverages();
        bv.show();
        this.hide();
    }//GEN-LAST:event_BVGBtnMousePressed

    private void btnMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMealActionPerformed

    private void btnMealMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealMouseMoved
        btnMeal.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_btnMealMouseMoved

    private void btnMealMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealMouseExited
        btnMeal.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnMealMouseExited

    private void btnMealMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealMousePressed
        Meal m= new Meal();
        m.show();
        this.hide();
// TODO add your handling code here:
    }//GEN-LAST:event_btnMealMousePressed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void btnCheckoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseEntered
        btnCheckout.setBackground(Color.RED);
    }//GEN-LAST:event_btnCheckoutMouseEntered

    private void btnCheckoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseExited
        btnCheckout.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnCheckoutMouseExited

    private void FFbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FFbtnMouseEntered
        FFbtn.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_FFbtnMouseEntered

    private void btnMealMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealMouseEntered
        btnMeal.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_btnMealMouseEntered

    private void APBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_APBTNMouseEntered
        APBTN.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_APBTNMouseEntered

    private void BVGBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BVGBtnMouseEntered
        BVGBtn.setBackground(new Color(0,102,0));
    }//GEN-LAST:event_BVGBtnMouseEntered

    private void FFbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FFbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FFbtnActionPerformed

    private void LogobtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogobtnMouseClicked
        Home hm = new Home();
        hm.show();
        this.hide();
    }//GEN-LAST:event_LogobtnMouseClicked
//bevarage end
    public void displayorder(){
    String qry="SELECT * FROM SALESORDER";
    try{
        conn=DriverManager.getConnection(connectionUrl, username, Pass);
    
      Statement st=conn.prepareStatement(qry);
      ResultSet rs=st.executeQuery(qry);
      
      while(rs.next()){
      String item   =String.valueOf(rs.getInt("ItemNo"));
      String Des   = rs.getString("Product");
      String qty   = String.valueOf(rs.getInt("QTY"));
      String price =String.valueOf(rs.getInt("Total"));
      String tbdata[]={item,Des,qty,price};
      DefaultTableModel model=(DefaultTableModel)ordertable.getModel();
      model.addRow(new Object[]{item,Des, qty, price});
      
    }
    }
    catch(SQLException e){
        e.printStackTrace();
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order_Details().setVisible(true);
            }
        });
    }
      public void GetTotal(){
       
       PreparedStatement pst = null;
       ResultSet rs = null;
       String qry = "Select Sum(Total) as sumprice from SALESORDER";
       
       try{
              conn = DriverManager.getConnection(connectionUrl, username, Pass);
              pst=conn.prepareStatement(qry);
              rs=pst.executeQuery();
             if(rs.next()){
                              String sum = rs.getString("sumprice");
                              //subtot.setText(sum);
                              int i=Integer.parseInt(sum);
                              int vattxt=(i/100*2);
                              int sertxt=(i/100*5);
                              int tottxt=(i/100*107);
                              String svat=String.valueOf(vattxt);
                              String sser=String.valueOf(sertxt);
                              String stot=String.valueOf(tottxt);
                              //vat.setText(svat);
                              //serv.setText(sser);
                              //tot.setText(stot);
             }
       }
       catch (SQLException ex) {
             ex.printStackTrace();
        }
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton APBTN;
    private javax.swing.JButton BVGBtn;
    private javax.swing.JButton FFbtn;
    private javax.swing.JButton Logobtn;
    private javax.swing.JPanel Sidepanel;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnMeal;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable ordertable;
    // End of variables declaration//GEN-END:variables

    
}
