/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodorderingsystem;

import java.awt.Color;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Neranji Sulakshika
 */
public class POPUP_Message_Submarine extends javax.swing.JFrame implements PopUpInterface_Fastfood {

    /**
     * Creates new form NewJFrame
     */
    
    //Declaration of Member Feilds    
    public final int CustID = 1000;
    String Total = "0";
    int qty; 
    String ProductDescription = "Submarine";
    Connection conn;
    
    //Connection setup
    String connectionUrl = "jdbc:mysql://localhost:3306/foodorderingsystem";
    String username= "sa";
    String Pass="anjalo9990";
    
    //Frame Creation
    public POPUP_Message_Submarine() {
        initComponents();
        // ProductDescription = Sltdropdown.getSelectedItem().toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblSubmarine = new javax.swing.JLabel();
        lblSubmarineName = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblLKR = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        spSubmarineQty = new javax.swing.JSpinner();
        lblTOTAL = new javax.swing.JLabel();
        lblTotalLKR = new javax.swing.JLabel();
        btnAddToPlateSubmarine = new javax.swing.JButton();
        lblSubmarineTotalPrice = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 530));
        jPanel1.setLayout(null);

        lblSubmarine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubmarine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SUBMARINE.jpg"))); // NOI18N
        jPanel1.add(lblSubmarine);
        lblSubmarine.setBounds(80, 40, 250, 170);
        lblSubmarine.getAccessibleContext().setAccessibleName("lblSubmarine");

        lblSubmarineName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblSubmarineName.setForeground(new java.awt.Color(0, 0, 0));
        lblSubmarineName.setText("SUBMARINE");
        jPanel1.add(lblSubmarineName);
        lblSubmarineName.setBounds(120, 220, 150, 30);
        lblSubmarineName.getAccessibleContext().setAccessibleName("lblSubmarineName");

        lblPrice.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(51, 51, 51));
        lblPrice.setText("200.00");
        jPanel1.add(lblPrice);
        lblPrice.setBounds(160, 260, 50, 20);
        lblPrice.getAccessibleContext().setAccessibleName("lblPrice");

        lblLKR.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblLKR.setForeground(new java.awt.Color(51, 51, 51));
        lblLKR.setText("LKR");
        jPanel1.add(lblLKR);
        lblLKR.setBounds(120, 260, 40, 20);
        lblLKR.getAccessibleContext().setAccessibleName("lblLKR");

        lblQty.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblQty.setForeground(new java.awt.Color(0, 0, 0));
        lblQty.setText("QTY");
        jPanel1.add(lblQty);
        lblQty.setBounds(50, 340, 50, 30);
        lblQty.getAccessibleContext().setAccessibleName("lblQty");

        spSubmarineQty.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        spSubmarineQty.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        spSubmarineQty.setBorder(null);
        spSubmarineQty.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        spSubmarineQty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spSubmarineQtyStateChanged(evt);
            }
        });
        jPanel1.add(spSubmarineQty);
        spSubmarineQty.setBounds(100, 340, 70, 30);
        spSubmarineQty.getAccessibleContext().setAccessibleName("spSubmarineQty");

        lblTOTAL.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblTOTAL.setForeground(new java.awt.Color(102, 102, 102));
        lblTOTAL.setText("TOTAL :");
        jPanel1.add(lblTOTAL);
        lblTOTAL.setBounds(190, 340, 60, 30);
        lblTOTAL.getAccessibleContext().setAccessibleName("lblTOTAL");

        lblTotalLKR.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblTotalLKR.setForeground(new java.awt.Color(51, 51, 51));
        lblTotalLKR.setText("LKR");
        jPanel1.add(lblTotalLKR);
        lblTotalLKR.setBounds(270, 340, 40, 30);
        lblTotalLKR.getAccessibleContext().setAccessibleName("lblTotalLKR");

        btnAddToPlateSubmarine.setBackground(new java.awt.Color(0, 153, 0));
        btnAddToPlateSubmarine.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnAddToPlateSubmarine.setForeground(new java.awt.Color(255, 255, 255));
        btnAddToPlateSubmarine.setText("ADD TO PLATE");
        btnAddToPlateSubmarine.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddToPlateSubmarine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddToPlateSubmarine.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnAddToPlateSubmarineStateChanged(evt);
            }
        });
        btnAddToPlateSubmarine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddToPlateSubmarineMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddToPlateSubmarineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddToPlateSubmarineMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddToPlateSubmarineMousePressed(evt);
            }
        });
        jPanel1.add(btnAddToPlateSubmarine);
        btnAddToPlateSubmarine.setBounds(90, 420, 210, 60);
        btnAddToPlateSubmarine.getAccessibleContext().setAccessibleName("btnAddToPlateSubmarine");

        lblSubmarineTotalPrice.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblSubmarineTotalPrice.setForeground(new java.awt.Color(51, 51, 51));
        lblSubmarineTotalPrice.setText("0.00");
        jPanel1.add(lblSubmarineTotalPrice);
        lblSubmarineTotalPrice.setBounds(310, 340, 50, 30);
        lblSubmarineTotalPrice.getAccessibleContext().setAccessibleName("lblSubmarineTotalPrice");

        btnCancel.setBackground(new java.awt.Color(255, 0, 0));
        btnCancel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("X");
        btnCancel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setPreferredSize(new java.awt.Dimension(181, 36));
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        jPanel1.add(btnCancel);
        btnCancel.setBounds(370, 10, 20, 20);
        btnCancel.getAccessibleContext().setAccessibleName("btnCancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(400, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // This page is not visible
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnAddToPlateSubmarineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddToPlateSubmarineMouseEntered
        // Changing the AddToPlateSubmarine button background color, when cursor move to the AddToPlateSubmarine button
        btnAddToPlateSubmarine.setBackground(Color.RED);
    }//GEN-LAST:event_btnAddToPlateSubmarineMouseEntered

    private void btnAddToPlateSubmarineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddToPlateSubmarineMouseExited
        // Rechange the AddToPlateSubmarine button background color, when cursor move out the AddToPlateSubmarine button
        btnAddToPlateSubmarine.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnAddToPlateSubmarineMouseExited

    private void btnAddToPlateSubmarineStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnAddToPlateSubmarineStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddToPlateSubmarineStateChanged

    private void btnAddToPlateSubmarineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddToPlateSubmarineMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddToPlateSubmarineMouseClicked

    private void btnAddToPlateSubmarineMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddToPlateSubmarineMousePressed
        // Adding number of Submarines to the plate
        if(qty == 0)
        {
           JOptionPane.showMessageDialog(null,"Sorry! Order can't be accepted, Please increase quantity to proceed..");
        }
        else 
        {
            CalculateFastfoodsPrice();  
            InsertOrderDetails();
        }
    }//GEN-LAST:event_btnAddToPlateSubmarineMousePressed

    private void spSubmarineQtyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spSubmarineQtyStateChanged
        // Calculate Submarines price
        CalculateFastfoodsPrice();
    }//GEN-LAST:event_spSubmarineQtyStateChanged

    // Declaration of Submarine Price
    @Override
    public double lblPrice() 
    {
        return 200.00;
    }

    //Declaration of member methods 
    @Override
    public void CalculateFastfoodsPrice() 
    {
        if(spSubmarineQty != null)
        {
            qty = (int) spSubmarineQty.getValue();
            
            if(qty > 20)
            {
                JOptionPane.showMessageDialog(null,"Sorry Order cant be Accepted , Please Talk to Staff..");                     
            }
            else
            {
                Total = Double.toString( qty * lblPrice());
           
                lblSubmarineTotalPrice.setText(Total);       
            }     
        }
         else if (spSubmarineQty ==  null)
              lblSubmarineTotalPrice.setText(Total);
         //Add a message box to add to cart 
    }    
    
    // Inserting the order details
    @Override
    public void InsertOrderDetails() 
    {
        String Insert;
        String Update;
        BigDecimal TotalValue = new BigDecimal(Total);
        
        try
        {    
        //Opening database for connection
            conn = DriverManager.getConnection(connectionUrl, username, Pass);
            Statement st = conn.createStatement();
            
            String sql="SELECT * FROM SALESORDER WHERE Product ='" + ProductDescription +"'";
            ResultSet rs = st.executeQuery(sql);
            
            if(rs.next())
            {
                Update="update SALESORDER set QTY= QTY + ?, Total= Total + ? where Product = ?";
                PreparedStatement pstmt = conn.prepareStatement(Update);
                pstmt.setInt(1,qty);
                pstmt.setBigDecimal(2,TotalValue);
                pstmt.setString(3,ProductDescription);
                pstmt.executeUpdate();
                pstmt.close();
                JOptionPane.showMessageDialog(null,"Sucessfully added to plate");
            }
            else
            { 
                Insert = "INSERT INTO SalesOrder (CustID, Product, QTY, Total) VALUES (?, ?, ?, ?)";
                PreparedStatement pstmt = conn.prepareStatement(Insert);
                pstmt.setInt(1,CustID);
                pstmt.setString(2, ProductDescription);
                pstmt.setInt(3, qty);
                pstmt.setBigDecimal(4, TotalValue);
                pstmt.executeUpdate();
                pstmt.close();
                JOptionPane.showMessageDialog(null,"Sucessfully Added to plate");
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Something went wrong\n");
            e.printStackTrace();
        }
        finally
        {
            try 
            {
                conn.close();
            } 
            catch (SQLException ex) 
            {
                Logger.getLogger(POPUP_Message_Submarine.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POPUP_Message_Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POPUP_Message_Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POPUP_Message_Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POPUP_Message_Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new POPUP_Message_Submarine().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToPlateSubmarine;
    private javax.swing.JButton btnCancel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLKR;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblSubmarine;
    private javax.swing.JLabel lblSubmarineName;
    private javax.swing.JLabel lblSubmarineTotalPrice;
    private javax.swing.JLabel lblTOTAL;
    private javax.swing.JLabel lblTotalLKR;
    private javax.swing.JSpinner spSubmarineQty;
    // End of variables declaration//GEN-END:variables

}
