/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodorderingsystem;

import static com.sun.corba.se.impl.naming.cosnaming.NamingUtils.printException;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dlsak
 */
public class Receipt extends javax.swing.JFrame {

    /**
     * Creates new form print
     */
    public Receipt() {
        initComponents();
       
    }
    
    public Receipt(String pay)
    {  
        initComponents();
        paytxt.setText(pay);
        
        displayorder();
        GetTotal();
        
    }
//Connection settings to database
    Connection conn;
    String connectionUrl = "jdbc:mysql://localhost:3306/foodorderingsystem";
    String username= "sa";
    String Pass="anjalo9990";

    Receipt(String payment, String order) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        paneltoprint = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblOrderType = new javax.swing.JLabel();
        subtot = new javax.swing.JLabel();
        vat = new javax.swing.JLabel();
        serv = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ordertable = new javax.swing.JTable();
        tot = new javax.swing.JLabel();
        Logobtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        paytxt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        paneltoprint.setBackground(new java.awt.Color(255, 255, 255));
        paneltoprint.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        paneltoprint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("RECIEPT");
        paneltoprint.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 170, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Servise Charge:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Sub Total           :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tax (VAT)          :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblOrderType.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblOrderType.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(lblOrderType, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 100, 30));

        subtot.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel3.add(subtot, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 90, 30));

        vat.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel3.add(vat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 70, 30));

        serv.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel3.add(serv, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 80, 30));

        paneltoprint.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 340, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Total           :");
        paneltoprint.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, -1, 30));

        ordertable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item No", "Product Description", "Qty", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ordertable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        ordertable.setAutoscrolls(false);
        ordertable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ordertable.setFillsViewportHeight(true);
        ordertable.setFocusable(false);
        ordertable.setGridColor(new java.awt.Color(255, 255, 255));
        ordertable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        ordertable.setRowHeight(25);
        ordertable.setSelectionBackground(new java.awt.Color(232, 57, 95));
        ordertable.setShowHorizontalLines(false);
        ordertable.setSurrendersFocusOnKeystroke(true);
        ordertable.setUpdateSelectionOnSort(false);
        jScrollPane3.setViewportView(ordertable);

        paneltoprint.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 400, 220));

        tot.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        paneltoprint.add(tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, 90, 30));

        Logobtn.setBackground(new java.awt.Color(255, 255, 255));
        Logobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N
        Logobtn.setBorder(null);
        paneltoprint.add(Logobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Paymant Type  :");
        paneltoprint.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 150, -1));

        paytxt.setText("payment type here");
        paneltoprint.add(paytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 565, -1, 20));

        jButton1.setText("PRINT");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(paneltoprint, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneltoprint, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(447, 773));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize.width, screenSize.height);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.hide();
    Thank_You_Message tk= new Thank_You_Message();
      tk.show();
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");

            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum>0){
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.24,0.24);

                paneltoprint.paint(g2);
//          

                return Printable.PAGE_EXISTS;
            }
    });

        boolean ok = job.printDialog();
        if(ok){
        try{

        job.print();
        }
        catch (PrinterException ex){}
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
public void displayorder(){
    String qry="SELECT * FROM SALESORDER";
    try{
        conn=DriverManager.getConnection(connectionUrl, username, Pass);
    
      Statement st=conn.prepareStatement(qry);
      ResultSet rs=st.executeQuery(qry);
      
      while(rs.next()){
      String item   =String.valueOf(rs.getInt("ItemNo"));
      String Des   = rs.getString("Product");
      String qty   = String.valueOf(rs.getInt("QTY"));
      String price =String.valueOf(rs.getInt("Total"));
      String tbdata[]={item,Des,qty,price};
      DefaultTableModel model=(DefaultTableModel)ordertable.getModel();
      model.addRow(new Object[]{item,Des, qty, price});
      
    }
    }
    catch(SQLException e){
        e.printStackTrace();
    }
    }
public void GetTotal(){
       
       PreparedStatement pst = null;
       ResultSet rs = null;
       String qry = "Select Sum(Total) as sumprice from SALESORDER";
       
       try{
              conn = DriverManager.getConnection(connectionUrl, username, Pass);
              pst=conn.prepareStatement(qry);
              rs=pst.executeQuery();
             if(rs.next()){
                              String sum = rs.getString("sumprice");
                              subtot.setText(sum);
                              int i=Integer.parseInt(sum);
                              int vattxt=(i/100*2);
                              int sertxt=(i/100*5);
                              int tottxt=(i/100*107);
                              String svat=String.valueOf(vattxt);
                              String sser=String.valueOf(sertxt);
                              String stot=String.valueOf(tottxt);
                              vat.setText(svat);
                              serv.setText(sser);
                              tot.setText(stot);
             }
       }
       catch (SQLException ex) {
             ex.printStackTrace();
        }
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logobtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel lblOrderType;
    private javax.swing.JTable ordertable;
    private javax.swing.JPanel paneltoprint;
    private javax.swing.JLabel paytxt;
    private javax.swing.JLabel serv;
    private javax.swing.JLabel subtot;
    private javax.swing.JLabel tot;
    private javax.swing.JLabel vat;
    // End of variables declaration//GEN-END:variables



}
